//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.SanbornsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SanbornsService.wCargaXmlSoap")]
    public interface wCargaXmlSoap {
        
        // CODEGEN: Generating message contract since element name Txtxml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarFacDigXml", ReplyAction="*")]
        WebApplication1.SanbornsService.CargarFacDigXmlResponse CargarFacDigXml(WebApplication1.SanbornsService.CargarFacDigXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarFacDigXml", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.SanbornsService.CargarFacDigXmlResponse> CargarFacDigXmlAsync(WebApplication1.SanbornsService.CargarFacDigXmlRequest request);
        
        // CODEGEN: Generating message contract since element name StrUser from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Seguridad", ReplyAction="*")]
        WebApplication1.SanbornsService.SeguridadResponse Seguridad(WebApplication1.SanbornsService.SeguridadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Seguridad", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.SanbornsService.SeguridadResponse> SeguridadAsync(WebApplication1.SanbornsService.SeguridadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarFacDigXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarFacDigXml", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.SanbornsService.CargarFacDigXmlRequestBody Body;
        
        public CargarFacDigXmlRequest() {
        }
        
        public CargarFacDigXmlRequest(WebApplication1.SanbornsService.CargarFacDigXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargarFacDigXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Txtxml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IdUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        public CargarFacDigXmlRequestBody() {
        }
        
        public CargarFacDigXmlRequestBody(string Txtxml, string IdUsuario, string Password) {
            this.Txtxml = Txtxml;
            this.IdUsuario = IdUsuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarFacDigXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarFacDigXmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.SanbornsService.CargarFacDigXmlResponseBody Body;
        
        public CargarFacDigXmlResponse() {
        }
        
        public CargarFacDigXmlResponse(WebApplication1.SanbornsService.CargarFacDigXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargarFacDigXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CargarFacDigXmlResult;
        
        public CargarFacDigXmlResponseBody() {
        }
        
        public CargarFacDigXmlResponseBody(string CargarFacDigXmlResult) {
            this.CargarFacDigXmlResult = CargarFacDigXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeguridadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Seguridad", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.SanbornsService.SeguridadRequestBody Body;
        
        public SeguridadRequest() {
        }
        
        public SeguridadRequest(WebApplication1.SanbornsService.SeguridadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeguridadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StrUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StrPass;
        
        public SeguridadRequestBody() {
        }
        
        public SeguridadRequestBody(string StrUser, string StrPass) {
            this.StrUser = StrUser;
            this.StrPass = StrPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeguridadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeguridadResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.SanbornsService.SeguridadResponseBody Body;
        
        public SeguridadResponse() {
        }
        
        public SeguridadResponse(WebApplication1.SanbornsService.SeguridadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeguridadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SeguridadResult;
        
        public SeguridadResponseBody() {
        }
        
        public SeguridadResponseBody(bool SeguridadResult) {
            this.SeguridadResult = SeguridadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wCargaXmlSoapChannel : WebApplication1.SanbornsService.wCargaXmlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wCargaXmlSoapClient : System.ServiceModel.ClientBase<WebApplication1.SanbornsService.wCargaXmlSoap>, WebApplication1.SanbornsService.wCargaXmlSoap {
        
        public wCargaXmlSoapClient() {
        }
        
        public wCargaXmlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wCargaXmlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wCargaXmlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wCargaXmlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.SanbornsService.CargarFacDigXmlResponse WebApplication1.SanbornsService.wCargaXmlSoap.CargarFacDigXml(WebApplication1.SanbornsService.CargarFacDigXmlRequest request) {
            return base.Channel.CargarFacDigXml(request);
        }
        
        public string CargarFacDigXml(string Txtxml, string IdUsuario, string Password) {
            WebApplication1.SanbornsService.CargarFacDigXmlRequest inValue = new WebApplication1.SanbornsService.CargarFacDigXmlRequest();
            inValue.Body = new WebApplication1.SanbornsService.CargarFacDigXmlRequestBody();
            inValue.Body.Txtxml = Txtxml;
            inValue.Body.IdUsuario = IdUsuario;
            inValue.Body.Password = Password;
            WebApplication1.SanbornsService.CargarFacDigXmlResponse retVal = ((WebApplication1.SanbornsService.wCargaXmlSoap)(this)).CargarFacDigXml(inValue);
            return retVal.Body.CargarFacDigXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.SanbornsService.CargarFacDigXmlResponse> WebApplication1.SanbornsService.wCargaXmlSoap.CargarFacDigXmlAsync(WebApplication1.SanbornsService.CargarFacDigXmlRequest request) {
            return base.Channel.CargarFacDigXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.SanbornsService.CargarFacDigXmlResponse> CargarFacDigXmlAsync(string Txtxml, string IdUsuario, string Password) {
            WebApplication1.SanbornsService.CargarFacDigXmlRequest inValue = new WebApplication1.SanbornsService.CargarFacDigXmlRequest();
            inValue.Body = new WebApplication1.SanbornsService.CargarFacDigXmlRequestBody();
            inValue.Body.Txtxml = Txtxml;
            inValue.Body.IdUsuario = IdUsuario;
            inValue.Body.Password = Password;
            return ((WebApplication1.SanbornsService.wCargaXmlSoap)(this)).CargarFacDigXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.SanbornsService.SeguridadResponse WebApplication1.SanbornsService.wCargaXmlSoap.Seguridad(WebApplication1.SanbornsService.SeguridadRequest request) {
            return base.Channel.Seguridad(request);
        }
        
        public bool Seguridad(string StrUser, string StrPass) {
            WebApplication1.SanbornsService.SeguridadRequest inValue = new WebApplication1.SanbornsService.SeguridadRequest();
            inValue.Body = new WebApplication1.SanbornsService.SeguridadRequestBody();
            inValue.Body.StrUser = StrUser;
            inValue.Body.StrPass = StrPass;
            WebApplication1.SanbornsService.SeguridadResponse retVal = ((WebApplication1.SanbornsService.wCargaXmlSoap)(this)).Seguridad(inValue);
            return retVal.Body.SeguridadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.SanbornsService.SeguridadResponse> WebApplication1.SanbornsService.wCargaXmlSoap.SeguridadAsync(WebApplication1.SanbornsService.SeguridadRequest request) {
            return base.Channel.SeguridadAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.SanbornsService.SeguridadResponse> SeguridadAsync(string StrUser, string StrPass) {
            WebApplication1.SanbornsService.SeguridadRequest inValue = new WebApplication1.SanbornsService.SeguridadRequest();
            inValue.Body = new WebApplication1.SanbornsService.SeguridadRequestBody();
            inValue.Body.StrUser = StrUser;
            inValue.Body.StrPass = StrPass;
            return ((WebApplication1.SanbornsService.wCargaXmlSoap)(this)).SeguridadAsync(inValue);
        }
    }
}
